// This file is auto-generated by FinalTagger. Do not modify it manually.
public static class Tags
{
    public static readonly string[] All = new string[]
    {
        "K",
        "DroneBotSpawnPoint",
        "PlayerSpawnPoint",
        "ConfinerBoundingBox",
        "AlienSpawnPoint",
        "CameraPoint",
        "Slayer",
        "SunLight",
        "Door",
        "Phone",
        "Door2",
        "SP2",
        "SP1",
        "SP3",
        "SP4",
    };
    public static class Ungrouped
    {
        public static readonly string[] All = new string[]
        {
            "K",
            "DroneBotSpawnPoint",
            "PlayerSpawnPoint",
            "ConfinerBoundingBox",
            "AlienSpawnPoint",
            "CameraPoint",
        };
        public const string K = "K";
        public const string DroneBotSpawnPoint = "DroneBotSpawnPoint";
        public const string PlayerSpawnPoint = "PlayerSpawnPoint";
        public const string ConfinerBoundingBox = "ConfinerBoundingBox";
        public const string AlienSpawnPoint = "AlienSpawnPoint";
        public const string CameraPoint = "CameraPoint";
    }
    public static class Pawn
    {
        public static readonly string[] All = new string[]
        {
            "Slayer",
        };
        public const string Slayer = "Slayer";
    }
    public static class Prop
    {
        public static readonly string[] All = new string[]
        {
            "SunLight",
        };
        public const string SunLight = "SunLight";
    }
    public static class Interactable
    {
        public static readonly string[] All = new string[]
        {
            "Door",
            "Phone",
            "Door2",
        };
        public const string Door = "Door";
        public const string Phone = "Phone";
        public const string Door2 = "Door2";
    }
    public static class Spawn
    {
        public static readonly string[] All = new string[]
        {
            "SP2",
            "SP1",
            "SP3",
            "SP4",
        };
        public const string SP2 = "SP2";
        public const string SP1 = "SP1";
        public const string SP3 = "SP3";
        public const string SP4 = "SP4";
    }
}
