// This file is auto-generated by FinalTagger. Do not modify it manually.
public static class Tags
{
    public static readonly string[] All = new string[]
    {
        "K",
        "DroneBotSpawnPoint",
        "PlayerSpawnPoint",
        "ConfinerBoundingBox",
        "AlienSpawnPoint",
        "CameraPoint",
        "ConfinerBoundingBox2",
        "Slayer",
        "Therionide",
        "SunLight",
        "Col1",
        "Prop1",
        "Door",
        "Phone",
        "Door2",
        "SP2",
        "SP1",
        "SP3",
        "SP4",
        "SP5",
        "SP6",
        "SP7",
    };
    public static class Ungrouped
    {
        public static readonly string[] All = new string[]
        {
            "K",
            "DroneBotSpawnPoint",
            "PlayerSpawnPoint",
            "ConfinerBoundingBox",
            "AlienSpawnPoint",
            "CameraPoint",
            "ConfinerBoundingBox2",
        };
        public const string K = "K";
        public const string DroneBotSpawnPoint = "DroneBotSpawnPoint";
        public const string PlayerSpawnPoint = "PlayerSpawnPoint";
        public const string ConfinerBoundingBox = "ConfinerBoundingBox";
        public const string AlienSpawnPoint = "AlienSpawnPoint";
        public const string CameraPoint = "CameraPoint";
        public const string ConfinerBoundingBox2 = "ConfinerBoundingBox2";
    }
    public static class Pawn
    {
        public static readonly string[] All = new string[]
        {
            "Slayer",
            "Therionide",
        };
        public const string Slayer = "Slayer";
        public const string Therionide = "Therionide";
    }
    public static class Prop
    {
        public static readonly string[] All = new string[]
        {
            "SunLight",
            "Col1",
            "Prop1",
        };
        public const string SunLight = "SunLight";
        public const string Col1 = "Col1";
        public const string Prop1 = "Prop1";
    }
    public static class Interactable
    {
        public static readonly string[] All = new string[]
        {
            "Door",
            "Phone",
            "Door2",
        };
        public const string Door = "Door";
        public const string Phone = "Phone";
        public const string Door2 = "Door2";
    }
    public static class Spawn
    {
        public static readonly string[] All = new string[]
        {
            "SP2",
            "SP1",
            "SP3",
            "SP4",
            "SP5",
            "SP6",
            "SP7",
        };
        public const string SP2 = "SP2";
        public const string SP1 = "SP1";
        public const string SP3 = "SP3";
        public const string SP4 = "SP4";
        public const string SP5 = "SP5";
        public const string SP6 = "SP6";
        public const string SP7 = "SP7";
    }
}
