// This file is auto-generated by FinalTagger. Do not modify it manually.
public static class Tags
{
    public static readonly string[] All = new string[]
    {
        "K",
        "Slayer",
        "Hero",
    };
    public static class Ungrouped
    {
        public static readonly string[] All = new string[]
        {
            "K",
        };
        public const string K = "K";
    }
    public static class Pawn
    {
        public static readonly string[] All = new string[]
        {
            "Slayer",
            "Hero",
        };
        public const string Slayer = "Slayer";
        public const string Hero = "Hero";
    }
}
